# Generated by Django 5.2.7 on 2026-03-06 16:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("_version", models.FloatField(default=1.0, verbose_name="内置版本号")),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "org_name",
                    models.CharField(
                        db_column="name",
                        help_text="社区组织名称",
                        max_length=50,
                        unique=True,
                        verbose_name="社区组织名称",
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(
                        help_text="组织联系人", max_length=20, verbose_name="组织联系人"
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        help_text="组织联系电话",
                        max_length=11,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_phone",
                                message="请输入有效的手机号码（11位数字，以13-19开头)",
                                regex="^1[3-9]\\d{9}$",
                            )
                        ],
                        verbose_name="组织联系电话",
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True,
                        help_text="社区联系邮箱",
                        max_length=254,
                        null=True,
                        verbose_name="社区联系邮箱",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="地址"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="社区组织描述", null=True, verbose_name="社区组织描述"
                    ),
                ),
                (
                    "org_avatar",
                    models.ImageField(
                        blank=True,
                        default="org_avatars/default_org_avatar.png",
                        help_text="组织头像",
                        null=True,
                        upload_to="org_avatars/",
                        verbose_name="组织头像",
                    ),
                ),
            ],
            options={
                "verbose_name": "社区组织",
                "verbose_name_plural": "社区组织",
                "db_table": "t_organization",
            },
        ),
    ]
