# Generated by Django 5.2.7 on 2026-03-29 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("goods_app", "0006_alter_goodscomments_goods"),
        ("organization_app", "0001_initial"),
        ("user_app", "0006_alter_userloginlog_login_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("_version", models.FloatField(default=1.0, verbose_name="内置版本号")),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "order_number",
                    models.CharField(
                        db_index=True, max_length=128, unique=True, verbose_name="订单编号"
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=64,
                        null=True,
                        verbose_name="第三方流水号",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (1, "待付款"),
                            (2, "待发货"),
                            (3, "待收货"),
                            (4, "待评价"),
                            (5, "已完成"),
                            (6, "已取消"),
                        ],
                        default=1,
                        verbose_name="订单状态",
                    ),
                ),
                (
                    "pay_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="支付时间"),
                ),
                (
                    "pay_method",
                    models.SmallIntegerField(
                        blank=True,
                        choices=[(1, "支付宝"), (2, "微信"), (3, "货到付款")],
                        null=True,
                        verbose_name="支付方式",
                    ),
                ),
                (
                    "good_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="商品单件价格",
                    ),
                ),
                ("good_count", models.IntegerField(default=1, verbose_name="商品数量")),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=14, verbose_name="订单总价"
                    ),
                ),
                (
                    "discount_price",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="优惠价格"
                    ),
                ),
                (
                    "freight_price",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="运费"
                    ),
                ),
                (
                    "pay_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="实际支付价格",
                    ),
                ),
                (
                    "order_remaining_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="订单剩余时间"),
                ),
                (
                    "courier_person",
                    models.CharField(
                        blank=True, max_length=32, null=True, verbose_name="快递员"
                    ),
                ),
                (
                    "courier_phone",
                    models.CharField(
                        blank=True, max_length=32, null=True, verbose_name="快递员手机号"
                    ),
                ),
                (
                    "courier_number",
                    models.CharField(
                        blank=True, max_length=128, null=True, verbose_name="快递单号"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="收货地址"
                    ),
                ),
                (
                    "delivery_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="发货时间"),
                ),
                (
                    "source",
                    models.IntegerField(
                        choices=[(1, "微信小程序"), (2, "H5"), (3, "App"), (4, "后台录入")],
                        default=1,
                        verbose_name="订单来源",
                    ),
                ),
                ("goods_name", models.CharField(max_length=255, verbose_name="商品名称快照")),
                (
                    "goods_spec",
                    models.CharField(
                        blank=True, max_length=128, null=True, verbose_name="商品规格快照"
                    ),
                ),
                (
                    "goods_image",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="商品主图快照"
                    ),
                ),
                (
                    "user_remark",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="用户备注"
                    ),
                ),
                (
                    "admin_remark",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="后台备注"
                    ),
                ),
                (
                    "goods",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="goods_order",
                        to="goods_app.goods",
                        verbose_name="商品",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_order",
                        to="organization_app.organization",
                        verbose_name="组织",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_order",
                        to="user_app.user",
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "订单表",
                "verbose_name_plural": "订单表",
                "db_table": "t_order",
                "indexes": [
                    models.Index(
                        fields=["user", "-create_time"],
                        name="t_order_user_id_e5dec6_idx",
                    ),
                    models.Index(
                        fields=["status", "-create_time"],
                        name="t_order_status_768589_idx",
                    ),
                    models.Index(
                        fields=["order_number"], name="t_order_order_n_8a04a4_idx"
                    ),
                ],
            },
        ),
    ]
