# Generated by Django 5.2.7 on 2026-03-29 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order_app", "0001_initial"),
        ("user_app", "0006_alter_userloginlog_login_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("_version", models.FloatField(default=1.0, verbose_name="内置版本号")),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "operator_name",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="操作人名称(快照)"
                    ),
                ),
                (
                    "action",
                    models.SmallIntegerField(
                        choices=[
                            (1, "创建订单"),
                            (2, "支付成功"),
                            (3, "商家发货"),
                            (4, "确认收货"),
                            (5, "取消订单"),
                            (6, "修改价格"),
                            (7, "修改地址"),
                            (8, "后台备注"),
                            (9, "系统超时"),
                        ],
                        verbose_name="操作类型",
                    ),
                ),
                (
                    "message",
                    models.TextField(blank=True, null=True, verbose_name="操作详情/变更内容"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="操作IP"
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="user_app.user",
                        verbose_name="操作人",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_logs",
                        to="order_app.order",
                        verbose_name="关联订单",
                    ),
                ),
            ],
            options={
                "verbose_name": "订单操作日志",
                "verbose_name_plural": "订单操作日志",
                "db_table": "t_order_log",
                "ordering": ["-create_time"],
                "indexes": [
                    models.Index(
                        fields=["order", "-create_time"],
                        name="t_order_log_order_i_0a4ec3_idx",
                    )
                ],
            },
        ),
    ]
