# Generated by Django 5.2.7 on 2026-04-03 23:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order_app", "0002_orderlog"),
        ("user_app", "0006_alter_userloginlog_login_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="是否删除"),
        ),
        migrations.AlterField(
            model_name="order",
            name="goods_spec",
            field=models.JSONField(
                blank=True, default=dict, null=True, verbose_name="商品规格快照"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="order",
            unique_together={("user", "order_number")},
        ),
    ]
