# Generated by Django 5.2.7 on 2026-04-07 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discount_app", "0002_coupontemplate_version_and_more"),
        ("order_app", "0003_order_is_deleted_alter_order_goods_spec_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="user_coupon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_coupon_order",
                to="discount_app.usercoupon",
                verbose_name="用户领取的优惠券",
            ),
        ),
    ]
