# Generated by Django 5.2 on 2026-07-30 18:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order_app", "0005_alipay_fields"),
        ("user_app", "0007_update_unique_error_messages"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="order",
            unique_together={("user", "order_number")},
        ),
        migrations.AddField(
            model_name="order",
            name="idempotency_key",
            field=models.CharField(
                blank=True, default=None, max_length=64, null=True, verbose_name="幂等键"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="order",
            unique_together={("user", "idempotency_key"), ("user", "order_number")},
        ),
    ]
