# Generated by Django 5.2 on 2026-07-31 11:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "order_app",
            "0006_alter_order_unique_together_order_idempotency_key_and_more",
        ),
    ]

    operations = [
        # Set existing NULL idempotency_key values to empty string so the
        # unique_together constraint on (user, idempotency_key) stays valid
        # when we change the column to NOT NULL.
        # For each row with a NULL idempotency_key, set it to a value that
        # is unique per user so the unique_together constraint on
        # (user, idempotency_key) stays valid when we go NOT NULL.
        migrations.RunSQL(
            sql="UPDATE t_order SET idempotency_key=CONCAT('mig_', id) WHERE idempotency_key IS NULL;",
            reverse_sql="",
        ),
        migrations.AlterField(
            model_name="order",
            name="idempotency_key",
            field=models.CharField(default="", max_length=64, verbose_name="幂等键"),
        ),
    ]
