# Generated by Django 5.2 on 2026-07-31 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order_app", "0007_alter_order_idempotency_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="idempotency_key",
            field=models.CharField(
                blank=True, default=None, max_length=64, null=True, verbose_name="幂等键"
            ),
        ),
    ]
