"""
Django settings for communityHub project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import logging
from logging.handlers import RotatingFileHandler, TimedRotatingFileHandler
from concurrent_log_handler import ConcurrentRotatingFileHandler
from datetime import time

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-_-h*sbe(tyjbjv=_+i6hd87xv8_df_1*qkq1gofi3!6=somt-6"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_filters',  # 快速实现复杂的查询过滤功能
    'rest_framework',  # 快速实现 RESTful API
    'corsheaders',  # 跨域请求
    "rest_framework_simplejwt",  # 添加JWT支持
    'mptt',  # 注册 django-mptt , 用 MPTTModel 替代 Django 原生的 models.Model，自动获得树形功能
    'drf_yasg',  # Swagger 文档
    'models',  # 基础模型
    'organization_app',  # 组织机构应用
    'user_app',  # 用户应用
    'goods_app',  # 商品应用
    'order_app',  # 订单应用
    'discount_app',  # 优惠券应用
    # 'django_celery_beat',  # 定时任务
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # 处理跨域请求 pip install django-cors-headers
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'communityHub.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'communityHub.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": 'communityHub',
        "USER": 'root',
        "PASSWORD": '123456',
        "HOST": '127.0.0.1',
        "PORT": "3306"
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Shanghai"

USE_I18N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# 静态文件的 URL 前缀（浏览器访问时的路径）
STATIC_URL = 'static/'

# 静态文件路径：
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static")  # 可存放多个静态文件路径
]

# 媒体文件
MEDIA_URL = 'media/'  # 访问用户上传文件的 URL 前缀
MEDIA_ROOT = BASE_DIR / 'media'  # 用户上传文件的根目录

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 静态文件路径：
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static")  # 可存放多个静态文件路径
]

# 生产环境下静态文件的收集目录（可选，部署时使用）
# 执行 collectstatic 命令后，所有静态文件会被复制到该目录
STATIC_ROOT = BASE_DIR / 'collected_static'

# CACHES = {
#     "default":{
#         "BACKEND": "django.core.cache.backends.redis.RedisCache",
#         "LOCATION": "redis://127.0.0.1:6379", # 缓存的地址
#         "TIMEOUT": 300,
#         "OPTIONS":{
#             "db":1,
#             # "PASSWORD": "123456",
#             'pool_class': 'redis.BlockingConnectionPool',  # 缓存的连接池
#         }
#     }
# }
#
# CACHE_MIDDLEWARE_ALIAS = "default"
# CACHE_MIDDLEWARE_SECONDS = 10 # 缓存的过期时间,10秒
# CACHE_MIDDLEWARE_KEY_PREFIX = "cache" # 缓存的键的前缀

# 如果是生产环境关闭全局允许（默认是 False，显式设置更安全）
CORS_ALLOW_ALL_ORIGINS = True  # 开发环境

# 允许的源列表
# CORS_ALLOWED_ORIGINS = [
#     "https://example.com",  # 生产域名
#     "https://api.example.com",  # 子域名
#     "https://www.example.com:8080",  # 带端口的域名（非默认端口必须指定）
# ]

# 允许跨域请求携带 cookies（需前端配合设置 withCredentials: true）
CORS_ALLOW_CREDENTIALS = True

# 允许的 HTTP 方法（按需添加）
CORS_ALLOW_METHODS = [
    "GET",
    "POST",
    "PUT",
    "PATCH",
    "DELETE",
    "OPTIONS",
]

# 允许的请求头（默认包含常见 headers，如需自定义 headers 需添加）
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",  # 如需 CSRF 保护，必须包含
    "x-requested-with",
    # "my-custom-header",  #自定义的header
]

# 允许前端访问的响应头（默认只暴露基本 headers）
# CORS_EXPOSE_HEADERS = [
#     "Content-Disposition",  # 例如文件下载时的文件名头
# ]

# 跨域请求的缓存时间（秒），减少 OPTIONS 预检请求次数
CORS_PREFLIGHT_MAX_AGE = 86400  # 24小时

# 日志配置
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',  # 处理器类型：标准输出流（控制台）
            'formatter': 'verbose',
        },
        # 'file': {
        #     'class': 'logging.FileHandler', # 处理器类型：文件存储
        #     'filename': os.path.join(Path(__file__).resolve().parent.parent.parent, 'logs/django.log'),
        #     'formatter': 'verbose', # 关联的格式：使用 'verbose' 详细格式
        #     'encoding': 'utf-8',
        # },
        # 'rotating_file_log': {
        #     'level': 'INFO',
        #     'class': 'logging.handlers.RotatingFileHandler',
        #     'filename': BASE_DIR/'logs'/'django.log',
        #     'maxBytes': 150 * 1024,  # 限制150KB
        #     'backupCount': 5,    # 保留5个备份文件
        #     'formatter': 'verbose',  # 格式：使用 'verbose' 详细格式
        #     'encoding': 'utf-8',
        # },
        'rotating_day_log': {
            'level': 'INFO',
            'class': 'concurrent_log_handler.ConcurrentRotatingFileHandler',
            'filename': BASE_DIR.parent / 'logs' / 'django.log',
            # 'when': 'M',
            # 'interval': 1, # 1天轮转1次
            # 'atTime':time(11,51),
            'maxBytes': 1024 * 300,  # 300KB
            'backupCount': 7,  # 保留7个备份文件
            'formatter': 'verbose',  # 格式：使用 'verbose' 详细格式
            'encoding': 'utf-8',
        }
    },
    'loggers': {  # 日志入口
        'django': {
            'handlers': ['console', 'rotating_day_log'],
            'level': 'INFO',
            'propagate': True,
        }
    }
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'user_app.authentication.BlacklistJWTAuthentication'
    ],
    'EXCEPTION_HANDLER': 'config.help_tools.common_exception_handler',
}

CACHE_KEY_IP_FAIL = "login_fail_ip_{}"  # 缓存登录失败的 Ip 次数
CACHE_KEY_REGISTER = "register_ip_{}"  # 缓存注册的 Ip
CACHE_KEY_ACCOUNT_FAIL = "fail_account_{}"  # 缓存同一账号次数
CACHE_KEY_CREATE_ORDER = "create_order_{}"  # 缓存创建订单

ACCOUNT_MAX_FAILS = 10  # 登录时候账号校验最大次数
IP_MAX_FAILS = 10  # 登录时候和注册账号 Ip 最大限制次数
MAX_CREATE_ORDER = 20  # 创建订单最大限制次数
LOCK_TIME = 60 * 30  # ip 锁定时间(30分钟)

MAX_REPLY_DISPLAY_COUNT = 5  # 商品评论回复显示最大数量（一次）
MAX_COMMENT_COUNT = 50  # 商品评论显示最大数量（一次）,再获取就刷新一次接口

# Celery 配置
CELERY_BROKER_URL = 'redis://127.0.0.1:6379/0'  # broker
CELERY_RESULT_BACKEND = 'redis://127.0.0.1:6379/2'  # backend
CELERY_RESULT_SERIALIZER = 'json'  # 结果序列化方案
CELERY_TASK_RESULT_EXPIRES = 60 * 60 * 24 * 7  # 结果过期时间
CELERY_TIMEZONE = 'Asia/Shanghai'

# 显式指定 Celery 任务所在的模块
CELERY_IMPORTS = [
    'celery_tasks.clear_expire_coupon',
]

# 告诉 Celery 使用 django_celery_beat 作为调度器
# CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'