# Generated by Django 5.2.7 on 2026-03-07 23:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organization_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("_version", models.FloatField(default=1.0, verbose_name="内置版本号")),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        default="默认用户",
                        help_text="用户名",
                        max_length=20,
                        null=True,
                        verbose_name="用户名",
                    ),
                ),
                (
                    "account",
                    models.CharField(
                        help_text="账号", max_length=20, unique=True, verbose_name="账号"
                    ),
                ),
                (
                    "password",
                    models.CharField(help_text="密码", max_length=20, verbose_name="密码"),
                ),
                (
                    "mobile",
                    models.CharField(
                        blank=True,
                        help_text="手机号",
                        max_length=11,
                        null=True,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_mobile",
                                message="请输入正确的手机号（11位）",
                                regex="^1[3-9]\\d{9}$",
                            )
                        ],
                        verbose_name="手机号",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="邮箱",
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="邮箱",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        default="user_avatars/default_user_avatar.png",
                        help_text="用户头像",
                        null=True,
                        upload_to="user_avatars/",
                        verbose_name="用户头像",
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, help_text="出生日", null=True, verbose_name="出生日"
                    ),
                ),
                (
                    "id_card",
                    models.CharField(
                        blank=True,
                        help_text="身份证号",
                        max_length=18,
                        null=True,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_id_card",
                                message="请输入合适的身份证号（18位）",
                                regex="^[1-9]\\d{5}(18|19|([23]\\d))\\d{2}((0[1-9])|(10|11|12))(([0-2][1-9])|10|20|30|31)\\d{3}[0-9Xx]$",
                            )
                        ],
                        verbose_name="身份证号",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="详细地址"
                    ),
                ),
                (
                    "building",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="楼栋"
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="单元"
                    ),
                ),
                (
                    "room",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="房号"
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="账户余额",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False, help_text="是否为管理员", verbose_name="是否为管理员"
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, help_text="最后登录时间", null=True, verbose_name="最后登录时间"
                    ),
                ),
                (
                    "last_login_ip",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to="organization_app.organization",
                        verbose_name="所属的社区组织",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
