# Generated by Django 5.2.7 on 2026-03-07 23:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "用户", "verbose_name_plural": "用户"},
        ),
        migrations.AlterModelTable(
            name="user",
            table="t_user",
        ),
    ]
