# Generated by Django 5.2.7 on 2026-03-08 17:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization_app", "0001_initial"),
        ("user_app", "0002_alter_user_options_alter_user_table"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="address",
        ),
        migrations.RemoveField(
            model_name="user",
            name="building",
        ),
        migrations.RemoveField(
            model_name="user",
            name="last_login_ip",
        ),
        migrations.RemoveField(
            model_name="user",
            name="room",
        ),
        migrations.RemoveField(
            model_name="user",
            name="unit",
        ),
        migrations.AddField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="False=禁用/拉黑账号", verbose_name="是否激活"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[("resident", "居民"), ("admin", "社区管理员"), ("vendor", "商户")],
                default="resident",
                max_length=10,
                verbose_name="用户类型",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="balance",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="账户余额",
                max_digits=10,
                verbose_name="账户余额",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(blank=True, null=True, verbose_name="最后登录时间"),
        ),
        migrations.AlterField(
            model_name="user",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="organization_app.organization",
                verbose_name="所属的社区组织",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(help_text="密码", max_length=256, verbose_name="密码"),
        ),
        migrations.CreateModel(
            name="UserLoginLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("_version", models.FloatField(default=1.0, verbose_name="内置版本号")),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "login_time",
                    models.DateTimeField(
                        auto_now_add=True, help_text="登录时间", verbose_name="登录时间"
                    ),
                ),
                (
                    "login_ip",
                    models.CharField(
                        help_text="登录的ip", max_length=50, verbose_name="登录的ip"
                    ),
                ),
                (
                    "login_status",
                    models.BooleanField(
                        default=True, help_text="True=成功，False=失败", verbose_name="登录状态"
                    ),
                ),
                (
                    "login_type",
                    models.CharField(
                        choices=[("pc", "电脑端"), ("mobile", "移动端"), ("admin", "后台管理端")],
                        default="mobile",
                        max_length=10,
                        verbose_name="登录端类型",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_login_log",
                        to="user_app.user",
                        verbose_name="用户登录日志",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户登录日志",
                "verbose_name_plural": "用户登录日志",
                "db_table": "t_user_login_log",
            },
        ),
        migrations.CreateModel(
            name="UserAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("_version", models.FloatField(default=1.0, verbose_name="内置版本号")),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("name", models.CharField(max_length=20, verbose_name="收货人姓名")),
                (
                    "mobile",
                    models.CharField(
                        max_length=11,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_mobile",
                                message="请输入正确的手机号（11位）",
                                regex="^1[3-9]\\d{9}$",
                            )
                        ],
                        verbose_name="手机号",
                    ),
                ),
                ("province", models.CharField(max_length=20, verbose_name="省")),
                ("city", models.CharField(max_length=20, verbose_name="市")),
                ("district", models.CharField(max_length=20, verbose_name="区")),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="详细地址"
                    ),
                ),
                (
                    "building",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="楼栋"
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="单元"
                    ),
                ),
                (
                    "room",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="房号"
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="是否默认地址"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_addresses",
                        to="user_app.user",
                        verbose_name="关联用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户配送地址",
                "verbose_name_plural": "用户配送地址",
                "db_table": "t_user_address",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_default", True)),
                        fields=("user", "is_default"),
                        name="unique_default_address",
                    )
                ],
            },
        ),
    ]
