# Generated by Django 5.2.7 on 2026-03-23 18:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_app", "0003_remove_user_address_remove_user_building_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("resident", "居民"),
                    ("seller", "商户"),
                    ("admin", "社区管理员"),
                    ("super_admin", "超管"),
                ],
                default="resident",
                max_length=100,
                verbose_name="用户类型",
            ),
        ),
    ]
