# Generated by Django 5.2.7 on 2026-03-25 16:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization_app", "0001_initial"),
        ("user_app", "0004_alter_user_user_type"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["-create_time"], name="t_user_create__e43ecd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["username"], name="t_user_usernam_072bae_idx"),
        ),
    ]
