# Generated by Django 5.2.7 on 2026-03-25 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_app", "0005_user_t_user_create__e43ecd_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userloginlog",
            name="login_status",
            field=models.CharField(
                help_text="登录|登出状态", max_length=20, verbose_name="登录|登出状态"
            ),
        ),
        migrations.AlterField(
            model_name="userloginlog",
            name="login_type",
            field=models.CharField(
                choices=[
                    ("normal_in", "正常登录"),
                    ("normal_out", "正常登出"),
                    ("normal_in_error", "登录失败"),
                    ("normal_out_error", "登出失败"),
                ],
                max_length=20,
                verbose_name="登录类型",
            ),
        ),
    ]
