# Generated by Django 5.2 on 2026-07-23 18:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_app", "0006_alter_userloginlog_login_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="account",
            field=models.CharField(
                error_messages={"unique": "该账号已被注册"},
                help_text="账号",
                max_length=20,
                unique=True,
                verbose_name="账号",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True,
                error_messages={"unique": "该邮箱已被注册"},
                help_text="邮箱",
                max_length=50,
                null=True,
                unique=True,
                verbose_name="邮箱",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="mobile",
            field=models.CharField(
                blank=True,
                error_messages={"unique": "该手机号已被注册"},
                help_text="手机号",
                max_length=11,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_mobile",
                        message="请输入正确的手机号（11位）",
                        regex="^1[3-9]\\d{9}$",
                    )
                ],
                verbose_name="手机号",
            ),
        ),
    ]
