# Generated by Django 5.2 on 2026-07-29 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("user_app", "0007_update_unique_error_messages"),
    ]

    operations = [
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("_version", models.FloatField(default=1.0, verbose_name="内置版本号")),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="账户余额",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet",
                        to="user_app.user",
                        verbose_name="关联用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户钱包",
                "verbose_name_plural": "用户钱包",
                "db_table": "t_wallet",
            },
        ),
        migrations.CreateModel(
            name="BalanceLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("_version", models.FloatField(default=1.0, verbose_name="内置版本号")),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "change_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="变动金额"
                    ),
                ),
                (
                    "balance_before",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="变动前余额"
                    ),
                ),
                (
                    "balance_after",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="变动后余额"
                    ),
                ),
                (
                    "source_type",
                    models.IntegerField(
                        choices=[(0, "充值"), (1, "消费"), (2, "退款"), (3, "后台调整")],
                        verbose_name="来源类型",
                    ),
                ),
                (
                    "source_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="来源ID（订单/充值单等）"
                    ),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="备注"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="balance_logs",
                        to="user_app.user",
                        verbose_name="关联用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "余额变动日志",
                "verbose_name_plural": "余额变动日志",
                "db_table": "t_balance_log",
                "indexes": [
                    models.Index(
                        fields=["user", "-create_time"],
                        name="t_balance_l_user_id_f40acf_idx",
                    ),
                    models.Index(
                        fields=["source_type"], name="t_balance_l_source__2ff85c_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RechargeOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("_version", models.FloatField(default=1.0, verbose_name="内置版本号")),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "recharge_number",
                    models.CharField(max_length=50, unique=True, verbose_name="充值订单号"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="充值金额"
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "待支付"), (1, "已支付"), (2, "支付失败"), (3, "已过期")],
                        default=0,
                        verbose_name="支付状态",
                    ),
                ),
                (
                    "pay_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="支付时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recharge_orders",
                        to="user_app.user",
                        verbose_name="关联用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "充值订单",
                "verbose_name_plural": "充值订单",
                "db_table": "t_recharge_order",
                "indexes": [
                    models.Index(
                        fields=["user", "-create_time"],
                        name="t_recharge__user_id_b5b99b_idx",
                    ),
                    models.Index(
                        fields=["status"], name="t_recharge__status_3a4bfd_idx"
                    ),
                ],
            },
        ),
    ]
