# Generated by Django 5.2 on 2026-07-29 17:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallet_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wallet",
            name="balance",
        ),
        migrations.AddField(
            model_name="balancelog",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="是否删除"),
        ),
    ]
