# Generated by Django 5.2.7 on 2026-04-04 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("order_app", "0003_order_is_deleted_alter_order_goods_spec_and_more"),
        ("organization_app", "0001_initial"),
        ("user_app", "0006_alter_userloginlog_login_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CouponTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("_version", models.FloatField(default=1.0, verbose_name="内置版本号")),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("name", models.CharField(max_length=50, verbose_name="优惠券名称")),
                ("description", models.CharField(max_length=100, verbose_name="优惠券描述")),
                (
                    "type",
                    models.SmallIntegerField(
                        choices=[(1, "满减券"), (2, "折扣券"), (3, "现金券")],
                        verbose_name="优惠券类型",
                    ),
                ),
                (
                    "min_purchase",
                    models.IntegerField(
                        default=0, help_text="0表示无门槛", verbose_name="最低消费金额(分)"
                    ),
                ),
                (
                    "discount",
                    models.FloatField(default=1, help_text="8表示八折", verbose_name="折扣"),
                ),
                (
                    "total_count",
                    models.IntegerField(
                        default=0, help_text="0表示不限制数量", verbose_name="优惠券总量"
                    ),
                ),
                (
                    "person_limit_count",
                    models.IntegerField(
                        default=0, help_text="0表示不限制数量", verbose_name="每人限领数量"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否激活")),
                (
                    "scope_desc",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="适用范围说明"
                    ),
                ),
                (
                    "valid_from",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="优惠劵模版生效时间"
                    ),
                ),
                (
                    "valid_to",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="优惠劵模版过期时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "优惠券模版",
                "verbose_name_plural": "优惠券模版",
                "db_table": "t_coupon_template",
                "indexes": [
                    models.Index(
                        fields=["-create_time"], name="t_coupon_te_create__237d1d_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="t_coupon_te_is_acti_c13823_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserCoupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("_version", models.FloatField(default=1.0, verbose_name="内置版本号")),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "used_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="使用时间"),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(0, "未使用"), (1, "已使用"), (2, "已过期"), (3, "已锁定")],
                        default=0,
                        verbose_name="优惠券状态",
                    ),
                ),
                (
                    "snapshot_value",
                    models.IntegerField(help_text="领券时的数值", verbose_name="优惠金额/折扣(快照)"),
                ),
                (
                    "snapshot_min_purchase",
                    models.IntegerField(default=0, verbose_name="最低消费(快照)"),
                ),
                ("valid_from", models.DateTimeField(verbose_name="生效时间")),
                ("valid_to", models.DateTimeField(verbose_name="过期时间")),
                (
                    "coupon_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="coupon_templates",
                        to="discount_app.coupontemplate",
                        verbose_name="优惠券模版",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_coupons",
                        to="order_app.order",
                        verbose_name="关联订单",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="organization_coupons",
                        to="organization_app.organization",
                        verbose_name="所属机构",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_coupons",
                        to="user_app.user",
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户优惠券",
                "verbose_name_plural": "用户优惠券",
                "db_table": "t_user_coupon",
            },
        ),
        migrations.CreateModel(
            name="CouponReceiveLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("_version", models.FloatField(default=1.0, verbose_name="内置版本号")),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "receive_type",
                    models.SmallIntegerField(
                        choices=[(1, "主动领取"), (2, "系统发放"), (3, "积分兑换")],
                        default=1,
                        verbose_name="领取方式",
                    ),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        default=1, help_text="1:成功, 0:失败", verbose_name="状态"
                    ),
                ),
                (
                    "ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="领取IP"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="organization_receive_logs",
                        to="organization_app.organization",
                        verbose_name="所属机构",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_receive_logs",
                        to="user_app.user",
                        verbose_name="用户",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="coupon_template_receive_logs",
                        to="discount_app.coupontemplate",
                        verbose_name="优惠券模版",
                    ),
                ),
                (
                    "user_coupon",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_coupon_receive_logs",
                        to="discount_app.usercoupon",
                        verbose_name="领取的优惠券",
                    ),
                ),
            ],
            options={
                "verbose_name": "优惠券领取记录",
                "db_table": "t_coupon_receive_log",
            },
        ),
        migrations.AddIndex(
            model_name="usercoupon",
            index=models.Index(
                fields=["user", "-create_time"], name="t_user_coup_user_id_a34a85_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usercoupon",
            index=models.Index(
                fields=["status", "-create_time"], name="t_user_coup_status_7ad394_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usercoupon",
            index=models.Index(
                fields=["coupon_template", "-create_time"],
                name="t_user_coup_coupon__e09dc3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="usercoupon",
            index=models.Index(
                fields=["organization", "-create_time"],
                name="t_user_coup_organiz_50276a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="usercoupon",
            index=models.Index(
                fields=["status", "valid_to"], name="t_user_coup_status_585a15_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="couponreceivelog",
            index=models.Index(
                fields=["user", "-create_time"], name="t_coupon_re_user_id_3e7f4c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="couponreceivelog",
            index=models.Index(
                fields=["template", "-create_time"],
                name="t_coupon_re_templat_5336a5_idx",
            ),
        ),
    ]
