# Generated by Django 5.2.7 on 2026-04-05 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discount_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupontemplate",
            name="version",
            field=models.SmallIntegerField(default=1, verbose_name="版本号"),
        ),
        migrations.AlterField(
            model_name="coupontemplate",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="是否激活"),
        ),
        migrations.AlterField(
            model_name="usercoupon",
            name="coupon_template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="template_coupons",
                to="discount_app.coupontemplate",
                verbose_name="优惠券模版",
            ),
        ),
    ]
