# Generated by Django 5.2 on 2026-07-31 22:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discount_app", "0002_coupontemplate_version_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupontemplate",
            name="discount_amount",
            field=models.IntegerField(
                default=0, help_text="0表示无优惠", verbose_name="优惠金额(元)"
            ),
        ),
        migrations.AlterField(
            model_name="coupontemplate",
            name="discount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("1.00"),
                help_text="8表示八折",
                max_digits=10,
                verbose_name="折扣",
            ),
        ),
        migrations.AlterField(
            model_name="coupontemplate",
            name="min_purchase",
            field=models.IntegerField(
                default=0, help_text="0表示无门槛", verbose_name="最低消费金额(元)"
            ),
        ),
        migrations.AlterField(
            model_name="usercoupon",
            name="snapshot_value",
            field=models.DecimalField(
                decimal_places=2,
                help_text="领券时的数值",
                max_digits=10,
                verbose_name="优惠金额/折扣(快照)",
            ),
        ),
    ]
