@access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc0MTAwNTYyLCJpYXQiOjE3NzQwMTQxNjIsImp0aSI6IjM2MmZhODhiZWQxYTQwMjRhYzhjMjA4ZjU2ZGYwM2MwIiwidXNlcl9pZCI6IjUifQ.xXu7hKNvmdLmCaYHqZBYSM3nLvDsOvPS2rTdWJBFGlw

### 用户登录
POST http://localhost:8000/user/user_login/
Content-Type: application/json

{
  "account": "2217518715",
  "password": "123456",
  "remember": true
}



### 注册用户
POST http://localhost:8000/user/user_create/
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "username": "久小孤",
  "account": "2217519715",
  "password": "123456",
  "password_confirm": "123456",
  "mobile": "13438881643",
  "email":"2217818715@qq.com",
  "birth_date": "2026-03-01",
  "id_card": "440982212712175993",
  "balance": 1000000.00,
  "is_active": true,
  "is_staff": true,
  "user_type": "admin",
  "organization_id": 1
}

### 获取用户信息
GET http://localhost:8000/user/user_retrieve/5/
Authorization: Bearer {{access_token}}

### 更新用户信息
PUT http://localhost:8000/user/user_retrieve/4/
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "username": "久孤",
  "account": "2217518615",
  "password": "123456",
  "password_confirm": "123456",
  "mobile": "13428871643",
  "email":"2217518615@qq.com",
  "birth_date": "2026-03-01",
  "id_card": "440982200712175893",
  "balance": 1000000.00,
  "organization_id": 1
}

### 删除用户
DELETE http://localhost:8000/user/user_retrieve/4/
Authorization: Bearer {{access_token}}

### 通过关键词查询用户
POST http://localhost:8000/user/user_list/
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
   "query_name":"久"
}