# Generated by Django 5.2.7 on 2026-03-20 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organization_app", "0001_initial"),
        ("user_app", "0003_remove_user_address_remove_user_building_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Goods",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("_version", models.FloatField(default=1.0, verbose_name="内置版本号")),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="商品名称", max_length=50, verbose_name="商品名称"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="商品价格",
                        max_digits=7,
                        verbose_name="商品价格",
                    ),
                ),
                (
                    "number",
                    models.IntegerField(
                        default=0, help_text="商品数量", verbose_name="商品数量"
                    ),
                ),
                (
                    "desc",
                    models.TextField(
                        blank=True, help_text="商品描述", null=True, verbose_name="商品描述"
                    ),
                ),
                (
                    "big_img",
                    models.ImageField(
                        blank=True,
                        default="goods_photos/default_goods_photos.png",
                        help_text="商品图片",
                        null=True,
                        upload_to="goods_photos/",
                        verbose_name="商品图片",
                    ),
                ),
                (
                    "small_img",
                    models.ImageField(
                        blank=True,
                        default="goods_photos/default_goods_photos.png",
                        help_text="商品缩略图",
                        null=True,
                        upload_to="goods_photos/",
                        verbose_name="商品缩略图",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待审核"),
                            ("normal", "已上架"),
                            ("offshelf", "下架"),
                            ("soldout", "售完"),
                        ],
                        help_text="商品状态",
                        max_length=10,
                        verbose_name="商品状态",
                    ),
                ),
                (
                    "sold_count",
                    models.IntegerField(
                        default=0, help_text="已售数量", verbose_name="已售数量"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="所属组织",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="org_goods",
                        to="organization_app.organization",
                        verbose_name="所属组织",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_goods",
                        to="user_app.user",
                        verbose_name="发布者",
                    ),
                ),
            ],
            options={
                "verbose_name": "商品",
                "verbose_name_plural": "商品",
                "db_table": "t_goods",
            },
        ),
        migrations.CreateModel(
            name="GoodsComments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("_version", models.FloatField(default=1.0, verbose_name="内置版本号")),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("comment", models.TextField(help_text="评论", verbose_name="评论")),
                (
                    "like",
                    models.IntegerField(default=0, help_text="点赞数", verbose_name="点赞数"),
                ),
                (
                    "reply",
                    models.TextField(
                        blank=True, help_text="回复", null=True, verbose_name="回复"
                    ),
                ),
                (
                    "comment_level",
                    models.IntegerField(
                        default=1, help_text="评论层级", verbose_name="评论层级"
                    ),
                ),
                (
                    "goods",
                    models.ForeignKey(
                        help_text="商品",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goods_comments",
                        to="goods_app.goods",
                        verbose_name="商品",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="用户",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_comments",
                        to="user_app.user",
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户评论",
                "verbose_name_plural": "用户评论",
                "db_table": "t_goods_comments",
            },
        ),
        migrations.AddIndex(
            model_name="goods",
            index=models.Index(fields=["status"], name="t_goods_status_d64c9b_idx"),
        ),
    ]
