# Generated by Django 5.2.7 on 2026-03-21 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goods_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="goodscomments",
            old_name="like",
            new_name="like_num",
        ),
        migrations.RemoveField(
            model_name="goodscomments",
            name="comment_level",
        ),
        migrations.RemoveField(
            model_name="goodscomments",
            name="reply",
        ),
        migrations.AddField(
            model_name="goodscomments",
            name="parents",
            field=models.ForeignKey(
                blank=True,
                help_text="商品的父评论",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="goods_app.goodscomments",
                verbose_name="商品的父评论",
            ),
        ),
    ]
