# Generated by Django 5.2.7 on 2026-03-23 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goods_app", "0002_rename_like_goodscomments_like_num_and_more"),
        ("organization_app", "0001_initial"),
        ("user_app", "0004_alter_user_user_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="goodscomments",
            old_name="parents",
            new_name="parent",
        ),
        migrations.CreateModel(
            name="GoodsLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("_version", models.FloatField(default=1.0, verbose_name="内置版本号")),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("goods_id", models.IntegerField(verbose_name="商品ID")),
                ("goods_name", models.CharField(max_length=255, verbose_name="商品名称")),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("create", "创建商品"),
                            ("update", "修改商品"),
                            ("delete", "删除商品"),
                            ("sold", "商品售出"),
                        ],
                        max_length=20,
                        verbose_name="操作类型",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="操作IP"
                    ),
                ),
                (
                    "remark",
                    models.TextField(blank=True, default="", verbose_name="操作备注/详情"),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="organization_app.organization",
                        verbose_name="所属组织",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="user_app.user",
                        verbose_name="操作人",
                    ),
                ),
            ],
            options={
                "verbose_name": "商品操作日志",
                "verbose_name_plural": "商品操作日志",
                "db_table": "t_goods_log",
                "ordering": ["-create_time"],
            },
        ),
    ]
