# Generated by Django 5.2.7 on 2026-03-25 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goods_app", "0003_rename_parents_goodscomments_parent_goodslog"),
        ("organization_app", "0001_initial"),
        ("user_app", "0004_alter_user_user_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="goodslog",
            old_name="operation",
            new_name="operation_type",
        ),
        migrations.CreateModel(
            name="GoodsCommentsLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("_version", models.FloatField(default=1.0, verbose_name="内置版本号")),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "comment_id_snapshot",
                    models.IntegerField(blank=True, null=True, verbose_name="评论ID快照"),
                ),
                (
                    "content_snapshot",
                    models.TextField(blank=True, null=True, verbose_name="评论内容快照"),
                ),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("delete", "用户自删"),
                            ("admin_delete", "管理员删除"),
                            ("ban", "屏蔽/折叠"),
                        ],
                        max_length=20,
                        verbose_name="操作类型",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="操作IP"
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True, help_text="操作原因", null=True, verbose_name="操作原因"
                    ),
                ),
                (
                    "comment",
                    models.ForeignKey(
                        blank=True,
                        help_text="商品评论",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="comment_log",
                        to="goods_app.goodscomments",
                        verbose_name="商品评论",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        help_text="操作用户",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="comment_log_user",
                        to="user_app.user",
                        verbose_name="操作用户",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="organization_app.organization",
                        verbose_name="所属组织",
                    ),
                ),
            ],
            options={
                "verbose_name": "商品评论操作日志",
                "verbose_name_plural": "商品评论操作日志",
                "db_table": "t_goods_comments_log",
                "ordering": ["-create_time"],
            },
        ),
    ]
