# Generated by Django 5.2.7 on 2026-03-28 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goods_app", "0004_rename_operation_goodslog_operation_type_and_more"),
        ("user_app", "0006_alter_userloginlog_login_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goodscomments",
            name="goods",
            field=models.ForeignKey(
                blank=True,
                help_text="商品",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="goods_comments",
                to="goods_app.goods",
                verbose_name="商品",
            ),
        ),
        migrations.AlterField(
            model_name="goodscomments",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="用户",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_comments",
                to="user_app.user",
                verbose_name="用户",
            ),
        ),
    ]
