# Generated by Django 5.2.7 on 2026-03-28 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goods_app", "0005_alter_goodscomments_goods_alter_goodscomments_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goodscomments",
            name="goods",
            field=models.ForeignKey(
                help_text="商品",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="goods_comments",
                to="goods_app.goods",
                verbose_name="商品",
            ),
        ),
    ]
