# Generated by Django 5.2.7 on 2026-04-03 23:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goods_app", "0006_alter_goodscomments_goods"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goods",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "待审核"),
                    ("normal", "已上架"),
                    ("offshelf", "已下架"),
                    ("soldout", "已售完"),
                ],
                default="待审核",
                help_text="商品状态",
                max_length=10,
                verbose_name="商品状态",
            ),
        ),
    ]
