# Generated by Django 5.2.7 on 2026-04-14 20:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goods_app", "0007_alter_goods_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="goods",
            name="is_hot",
            field=models.BooleanField(
                default=False, help_text="是否热门", verbose_name="是否热门"
            ),
        ),
    ]
