# Generated by Django 5.2 on 2026-07-23 17:06

import django.db.models.deletion
import goods_app.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goods_app", "0008_goods_is_hot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goods",
            name="big_img",
            field=models.ImageField(
                blank=True,
                default="goods_photos/default_goods_photos.png",
                help_text="商品主图（第一张）",
                null=True,
                upload_to=goods_app.models.goods_image_upload_path,
                verbose_name="商品主图",
            ),
        ),
        migrations.AlterField(
            model_name="goods",
            name="small_img",
            field=models.ImageField(
                blank=True,
                default="goods_photos/default_goods_photos.png",
                help_text="商品缩略图",
                null=True,
                upload_to=goods_app.models.goods_image_upload_path,
                verbose_name="商品缩略图",
            ),
        ),
        migrations.CreateModel(
            name="GoodsImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("_version", models.FloatField(default=1.0, verbose_name="内置版本号")),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=goods_app.models.goods_image_upload_path,
                        verbose_name="商品图片",
                    ),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "goods",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extra_images",
                        to="goods_app.goods",
                        verbose_name="所属商品",
                    ),
                ),
            ],
            options={
                "verbose_name": "商品图片",
                "verbose_name_plural": "商品图片",
                "db_table": "t_goods_image",
                "ordering": ["sort_order", "id"],
            },
        ),
    ]
