# Generated by Django 5.2 on 2026-07-26 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goods_app", "0009_alter_goods_big_img_alter_goods_small_img_goodsimage"),
        ("user_app", "0007_update_unique_error_messages"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommentLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("_version", models.FloatField(default=1.0, verbose_name="内置版本号")),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="goods_app.goodscomments",
                        verbose_name="被赞评论",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment_likes",
                        to="user_app.user",
                        verbose_name="点赞用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "评论点赞记录",
                "verbose_name_plural": "评论点赞记录",
                "db_table": "t_comment_like",
                "unique_together": {("user", "comment")},
            },
        ),
    ]
